# Generated by Django 4.1.5 on 2024-01-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sound", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Herbivore"),
                            ("2", "Carnivore"),
                            ("3", "Omnivore"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("species", models.CharField(blank=True, max_length=100, null=True)),
                ("habitat", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
